### ISSUE TITLE
Arrow is not visible when item is selected

### ISSUE THREAD

**Issue by bhushan** [jiyuan0125/Github3#1]
<img width="247" alt="Screenshot 2021-05-03 at 12 46 08 AM" src="https://user-images.githubusercontent.com/43483545/116824664-06fd0500-aba9-11eb-8b08-46b141aa2094.png">
<img width="247" alt="Screenshot 2021-05-03 at 12 46 14 AM" src="https://user-images.githubusercontent.com/43483545/116824667-08c6c880-aba9-11eb-9093-8497e631c570.png">

Check `Atom Material Icon Settings`, This basically happens for all dropdowns with an arrow.

**Comment by jiyuan0125** [comment]
This problem seems to come from the icon plug-in. The same problem exists when I use the default light theme.

**Comment by bhushan** [comment]
Do you mean default phpstorm thing ? Because i dont have any icon plugin installed still issue persists.. That means its something wrong with the dropdown colour pallet of this theme!!

**Comment by jiyuan0125** [comment]
I mean, when the icon plug-in is used, the Github3 theme behaves the same as the default Intellij light theme. The following figures are for comparison.

What they looks like before installing the plugin:
![e67875d67df440447e7525995434d27](https://user-images.githubusercontent.com/25894388/123885965-0b635580-d981-11eb-86bf-a3b2fe72c5b9.png)
![79d3de9a58dfa53428159810f61b032](https://user-images.githubusercontent.com/25894388/123885970-0dc5af80-d981-11eb-961c-d28dec86e3e7.png)

And what they looks like after installing the plugin:
![d63bd2cc8bbc488b1ce106b9f5abdef](https://user-images.githubusercontent.com/25894388/123886079-3f3e7b00-d981-11eb-8eca-e20414d9a55f.png)
![8a82e21a89e534c30c84744d1118886](https://user-images.githubusercontent.com/25894388/123886080-3fd71180-d981-11eb-8f3e-80f4192ac111.png)

**Comment by bhushan** [comment]
What could be the fix? If you dont have time guide me.. I will raise PR

**Comment by jiyuan0125** [comment]
When I uninstalled the icon plug-in, this problem disappeared.

To be compatible with the icon plug-in, the solution I can think of is to modify the background color of the selection.

If you have a better plan, PR is welcome.

**Comment by bhushan** [comment]
Actually it was problem with icon plugin when i removed it it just works .. But still thnx
