### ISSUE TITLE
Why Plugin name is Github3 instead of Github only ?

### ISSUE THREAD

**Issue by bhushan** [jiyuan0125/Github3#20]
It is more of a discussion question. We couldn’t we change plugin name ?

**Comment by jiyuan0125** [comment]
The light theme code comes from https://plugins.jetbrains.com/plugin/12271-github-3-color-scheme, I made few changes to the color. I don't understand why he called this github3, I think he is at least professional. I guess this is the third edition theme color of github. We can change the name of the theme, but I’m not sure if it’s a good experience for existing users.

**Comment by bhushan** [comment]
Okay, So we could rename it right ? 

but before that, Will it effect people like us who have installed this plugin already with Github3 name ?

**Comment by jiyuan0125** [comment]
Yes, I think we can. You know the result after you do it, don’t you? Ha ha! Even if there is a problem, the worst case is just to change back to the original name.

**Comment by bhushan** [comment]
I think its not super important now, we keep it on hold. 

I am actually waiting for v1.1.0 but seems like it will not have Github3 Light theme, Could you please take a look at https://github.com/jiyuan0125/Github3/issues/22

Also when I will get Latest version from Jetbrains Store ? I am eager to try it out.

**Comment by bhushan** [comment]
https://github.com/jiyuan0125/Github3/commit/cb2b2277ab86d3665b9fc1892c4a3f70f0ec4ef1 fixes this issues, only project ID is kept with github3 as it will be linked with Jetbrains Store
