### ISSUE TITLE
Dark color Changed to completely White !

### ISSUE THREAD

**Issue by annihilatorrrr** [jiyuan0125/Github3#206]
After updating my theme which was Github Dark Dimmed, which was having dark color in in files but now it's all bright uff, please fix it back.

**Comment by annihilatorrrr** [comment]
![buggg](https://github.com/user-attachments/assets/b651f453-3b67-4ea4-805a-17c210637661)

**Comment by svenluijten** [comment]
Running into the same issue. I'm using "GitHub Dark Dimmed" for both the theme and the editor color scheme, but the editor itself falls back to PhpStorm's standard "Light" theme.

![image](https://github.com/user-attachments/assets/ab71f571-2504-42c0-b4dc-192d0c1df7a9)

This started happening after updating to the most recent version (v1.2.2) with PhpStorm version 2024.1.5.

**Comment by annihilatorrrr** [comment]
@bhushan please fix it, too much pain in my eyes -_-

**Comment by annihilatorrrr** [comment]
Thanks @svenluijten :)
