### ISSUE TITLE
Update About section and links to navigate to theme

### ISSUE THREAD

**Issue by bhushan** [jiyuan0125/Github3#21]
<img width="309" alt="Screenshot 2021-08-08 at 1 26 17 PM" src="https://user-images.githubusercontent.com/43483545/128625179-1f9c7e43-9f7a-4b14-9547-114db0351b76.png">

@jiyuan0125 Please update about and links sections with tags so theme could be searched easily.

I have updated read me. About section you only have to update it.

You could take inspiration from https://github.com/primer/github-vscode-theme here.

**Comment by jiyuan0125** [comment]
I filled in a piece of descriptive information. What does "with tags" mean? I do not understand. :)

**Comment by bhushan** [comment]
Check screenshot there are tags light, dark, vscode .. while filling about section and description you will get this dropdown.. on project page check top right section, you will see about section

**Comment by jiyuan0125** [comment]
My God, I didn't notice that there was an "about" there. 😂 I have completed it.

**Comment by bhushan** [comment]
You could have added more tags and information but its fine for now. closing this issue

**Comment by bhushan** [comment]
I’ll bring some of my frnds to repo once we have release ready version

**Comment by jiyuan0125** [comment]
Welcome your friends to join! There is a saying in China that everyone gathers firewood and the flames are high. Hope that with our joint efforts, this project will be done well.

If the replacement of logo is not that important, let's release a new version now. What is your suggestion?

**Comment by bhushan** [comment]
Lets release it, but using that release hook only, that way i could also
release prereleases and new tags properly.. so in short lets focus on
automation task, i also saw you are working on dark theme 👍🏻 I will
automate change log process in weekend.
