### ISSUE TITLE
For some reason Github3 Light Theme is not visible 

### ISSUE THREAD

**Issue by bhushan** [jiyuan0125/Github3#22]
https://github.com/jiyuan0125/Github3/releases/tag/untagged-b41beae9f402435cf0fa

Tried it on 2, 3 machines.

**Comment by jiyuan0125** [comment]
![image](https://user-images.githubusercontent.com/25894388/128630196-d4406d94-8836-4d80-8b3c-83f297714a29.png)
Check if there is a light theme.

**Comment by jiyuan0125** [comment]
I forgot to mention it to you, I can’t wait to publish v1.1.0 to the store before you join this project. Ha ha! So we should release v 1.1.1, or another version.

**Comment by bhushan** [comment]
Install it from build assets from release, its not showing up, i took help of two friends too, on their machine as well its not showing up ..

**Comment by bhushan** [comment]
More info: I see from screenshot you are using intelij but i use phpstorm, all three test machines where phpstorm!!

**Comment by bhushan** [comment]
<img width="358" alt="Screenshot 2021-08-08 at 5 19 31 PM" src="https://user-images.githubusercontent.com/43483545/128630969-b834af77-2de5-400b-a9b0-dc068fe30d70.png">


uninstalled everything, and used latest build, still not working

**Comment by jiyuan0125** [comment]
![image](https://user-images.githubusercontent.com/25894388/128633763-18565755-0af4-4c39-b0c9-4366f8946d07.png)

Like yours, the problem is reproduced here. You can restore this value to "Default" and try again.

**Comment by bhushan** [comment]
It worked, actually i tried this before but i was trying with `default` which is wrong, with `Default` it worked
