### ISSUE TITLE
Outdated screenshots

### ISSUE THREAD

**Issue by bhushan** [jiyuan0125/Github3#23]
Screenshots are outdated needs update, also language specific screenshots will be nice to have. Java, JavaScript, PHP, Ruby, Go these could be added for now as these are popular languages these days also python.. 

Basically the languages which are supported by Jetbrains!!

**Comment by jiyuan0125** [comment]
I added some screenshots in the branch feature/screenshot. These screenshots do not seem to express the beauty of GitHub Theme, because my monitor resolution is not very high. Review when you have time.

**Comment by bhushan** [comment]
I liked those screenshots, in my opinion we should merge it and in my opinion we can make things perfect and invest 2 months or we can add minor better update and push it to production to get the feedback. I like second option more.

**Comment by bhushan** [comment]
Python not working @jiyuan0125

**Comment by bhushan** [comment]
I'll fix it after sometime, awesome screenshots and i like the idea of more link 👌🏻, you rock 🤘🏻

**Comment by bhushan** [comment]
I have updated all images to focus more on code styles.
