### ISSUE TITLE
Replace Github to GitHub in all applicable places

### ISSUE THREAD

**Issue by bhushan** [jiyuan0125/Github3#25]
Replace Github to GitHub in all applicable places in project

Also 

If possible change repository name to `github-theme-for-jetbrains` or `jetbrains-github-theme` something like that, so we could get some SEO benefits

**Comment by bhushan** [comment]
Actually, Its safe and easy to do it now, once we have little bit of traction from people then it will become difficult, so increased priority.

**Comment by jiyuan0125** [comment]
Done. 😀 e0f4878
