### ISSUE TITLE
[Feature Request] Dark mode

### ISSUE THREAD

**Issue by mattalexander-pantheon** [jiyuan0125/Github3#29]
That's the one I've been looking around for for JetBrains IDEs.

If I get some free Saturday, I'll see if I can do it and PR.

Thanks.

By the way, this is me: https://plugins.jetbrains.com/plugin/15418-github-theme/reviews#review=57715

Thanks again, my IDE looks great!

**Comment by jiyuan0125** [comment]
Thank you very much for your recognition of this project. Welcome to join this project.

I see your rating for this plugin, this is our motivation to move on.

In fact, I recently wrote some code for the Default Dark theme in the feature/dark-mode branch. I haven't decided what color to use for Selection's background, so I haven't released it.

**Comment by bhushan** [comment]
@mattalexander-pantheon you can take inspiration from feature/dark-mode branch for your PR..

**Comment by bhushan** [comment]
BETA version released https://github.com/bhushan/github-theme-for-jetbrains/pull/35
