### ISSUE TITLE
Automate Jar build on merging PR

### ISSUE THREAD

**Issue by bhushan** [jiyuan0125/Github3#4]
https://twitter.com/rckstrbhushan/status/1423595784600051712?s=21

Want to something like this for this project !! Is it possible, because i find it difficult to build jar and all, i could help you correct colours, if something in tweet is achieved

**Comment by jiyuan0125** [comment]
Thanks again for your support!

I just submitted some changes, using gradle to manage the project, and how to build the theme is mentioned in the README. If you have any questions, please feel free to reply to me.

**Comment by bhushan** [comment]
You are too fast !! :) 

Although on my fork build is failing, https://github.com/jiyuan0125/Github3/pull/6 sent this PR to test pull request build

allow write access and then hopefully we have a workflow which could be used to extend this project with multiple contributors

**Comment by bhushan** [comment]
<img width="1258" alt="Screenshot 2021-08-07 at 1 02 16 PM" src="https://user-images.githubusercontent.com/43483545/128592546-ff8fe2b7-c01c-4c32-b96a-8be4aa757ca8.png">

**Comment by jiyuan0125** [comment]
This is the first time I have encountered this problem. In fact, this is the first time I use this feature on Github. I made a modification according to the solution mentioned in the link below, hoping to solve this problem.

https://forum.gitlab.com/t/gradlew-permission-denied/20881

**Comment by bhushan** [comment]
Checking again @jiyuan0125, Also this weekend I would like to work on this project, I couldn't find you on twitter or linkedin, Is there any way I can contact you to ask questions if any, Obviously if that dont disturbs you :)

**Comment by jiyuan0125** [comment]
Thanks for your hard work.

I don’t have an account yet, and access to those websites is restricted.

You can contact me by email: jiyuan0125@126.com.

**Comment by bhushan** [comment]
> This is the first time I have encountered this problem. In fact, this is the first time I use this feature on Github. I made a modification according to the solution mentioned in the link below, hoping to solve this problem.
> 
> https://forum.gitlab.com/t/gradlew-permission-denied/20881

Solution worked, but now we have new error, 
<img width="1124" alt="Screenshot 2021-08-07 at 1 47 09 PM" src="https://user-images.githubusercontent.com/43483545/128593784-0b46fde7-b640-42a0-a55e-714793594ea0.png">

**Comment by jiyuan0125** [comment]
My pr #11 test passed. Try again when you are free.

**Comment by bhushan** [comment]
Its actually stoping execution of verify and release draft, I checked it already

**Comment by bhushan** [comment]
Proposal: 

https://github.com/JetBrains/intellij-platform-plugin-template

Use this template, It is first party template provided by Jetbrains, It will automate everything,

Everything means
- whenever new PR is merged It will generate latest plugin
- Whenever you add `prerelease` tag or `release` theme will be automatically published to Jetbrains Store

It will make life so much easy for us and we can only focus on `theme` which is primary outcome we want.

**Comment by bhushan** [comment]
This could be closed, @jiyuan0125 What do you think ? We have achieved automation now.

**Comment by bhushan** [comment]
When merging Changes, I dont see release draft, and also atleast once we should test `release` before closing this issue

**Comment by jiyuan0125** [comment]
You should have worked late last night, pay attention to sleep, brother! :)

I also noticed that you asked this question and someone gave an answer.
https://github.com/JetBrains/intellij-platform-plugin-template/issues/165

I was suddenly asked by the company to work overtime today, so I didn't reply to your message in time.

Yes, we should test the release, and we can perform this test now.

**Comment by bhushan** [comment]
Actually i wont be available in weekdays, so i am trying to make progress for this project as much as possible 😅 

Also if you have seen it, then i have created one project, check comments i am trying to setup project as i dont have enough access to this project to test things.. but builds are not working .. and i couldnt figure out much as i have not worked on java since 6 years 


Also locally i am using m1 MacBook pro, so project setup for trying colors has became tedious 😒.. m1 sucks, my old MacBook pro was gold

**Comment by bhushan** [comment]
> You should have worked late last night, pay attention to sleep, brother! :)

Thank you for it 🙏🏻

**Comment by bhushan** [comment]
have you updated https://github.com/jiyuan0125/Github3/blob/fc3b25d8b0d1b38db47ec5164234de7c7007a4ae/.github/workflows/release.yml#L33 PUBLISH_TOKEN as well @jiyuan0125 ?

**Comment by jiyuan0125** [comment]
I have added the environment secret, but I am not sure I am doing it correctly.

**Comment by bhushan** [comment]
Only you could do it, i dont have access to it, check "./gradlew publishPlugin" command docs

**Comment by bhushan** [comment]
<img width="843" alt="Screenshot 2021-08-08 at 11 46 21 PM" src="https://user-images.githubusercontent.com/43483545/128641679-cc2b2422-8db0-4c0f-8055-d12e710b1169.png">

**Comment by bhushan** [comment]
also we need to update `README.md` file https://github.com/jiyuan0125/Github3/blob/cb2b2277ab86d3665b9fc1892c4a3f70f0ec4ef1/build.gradle.kts#L107

because it parses it for change logs, we could change it to use `CHANGELOG.md` file

**Comment by jiyuan0125** [comment]
![image](https://user-images.githubusercontent.com/25894388/128997288-a3587f15-4ac1-4ccf-bca3-b243056cf314.png)

The automatic publishing function has been tested.

**Comment by bhushan** [comment]
Will close it once we have 1.1.1 in marketplace (store) 🤘🏻

**Comment by jiyuan0125** [comment]
Since I couldn't control the format of What's new, and only the version update log could be filled in that position, the statement of thanks was finally removed.

![image](https://user-images.githubusercontent.com/25894388/129019765-88f3633f-e34b-4142-91c7-bd7f64c4a16f.png)

**Comment by bhushan** [comment]
No problem

**Comment by bhushan** [comment]
I just wanted to make better which I already like 😅 and now its all aligned to my taste .. and i am liking it 🤘🏻 thank you for support

**Comment by jiyuan0125** [comment]
It turns out that all you like are good things. This is my chance to learn. 😁
