### ISSUE TITLE
Incorrect method parameter color for Java

### ISSUE THREAD

**Issue by napsterv** [jiyuan0125/Github3#55]
How it looks in IntelliJ:

![github-theme-1](https://user-images.githubusercontent.com/8555852/152651430-ca246227-3d53-440b-bde9-d8189e49f3a5.png)

How it looks in GitHub:
![github-theme-2](https://user-images.githubusercontent.com/8555852/152651431-7bc60300-1208-4ce7-b4e1-9f61c032d886.png)

**Comment by bhushan** [comment]
Thank you for reaching out @napsterv  but I am also trying to keep better contrast so it is easily / nicely visible to devs.

So, not sure what actually looks on GitHub is good, feel free to reopen issue or comment out if you want to say something via comment.
