### ISSUE TITLE
The selected item's text is too dark to be read

### ISSUE THREAD

**Issue by Aeldit** [jiyuan0125/Github3#56]
![Screenshot (23)](https://user-images.githubusercontent.com/81476169/152850869-d8de980a-801f-4b2b-9eb1-5ea9922e13df.png)
As you can see (or not :)) there, the selected parameter is 'Plugins', but the text is too dark
PS : I'm using PyCharm Community

**Comment by bhushan** [comment]
~~Thank you @Raphoulfifou  for reaching out, will be more than happy to accept your PR regarding this issue.~~

**Comment by bhushan** [comment]
![Screenshot 2022-03-04 at 9 22 16 PM](https://user-images.githubusercontent.com/43483545/156795796-cc32e70a-22f1-4ce8-a4c0-90f279aaedab.png)


I was trying to debug it, If you see in screenshot, its fine @Raphoulfifou ,, I think you have installed material theme and on top of it, you are using our theme. Please select only one and try it out..

**Comment by Aeldit** [comment]
yep, that was the problem. thanks :)
