### ISSUE TITLE
[Feature Request]: An average between dimmed and completely black

### ISSUE THREAD

**Issue by manuelpoelzl** [jiyuan0125/Github3#80]
This theme is really great and a real enrichment!
I would be interested to know if it would be possible to consider a version of the dark theme that is exactly a middle ground between the dimmed and the completely black theme. Maybe it could even replace the completely black theme.

I think variations of gray would be good, rather than really just pure black, that would be more appealing to the eyes.

Something like the vscode theme does, those shades of gray would be perfect.

In the screenshot here, you can see the vscode theme.

Maybe that could be considered at some point?

Otherwise, really a great theme!
![Color Scheme](https://user-images.githubusercontent.com/46539758/166835173-9cf801ea-b241-46d3-ae60-5da9ef6db788.png)

**Comment by bhushan** [comment]
@manuelpoelzl i personally love dimmed version.. but there was request from people to have complete dark mode.. I would be more than happy if you submit any new theme as PR.. but don't modify  existing one..

**Comment by manuelpoelzl** [comment]
@bhushan I will see what I can do  👍
